<a href="https://colab.research.google.com/github/ShatakshiR/PythonDemo/blob/master/pandas_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('pandas_demo_data/insurance.csv')
data

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
#top 5 rows of the data
data.head(5)

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [9]:
# bottom 10 rows of the data
data.tail(10)

      age  gender     bmi  children smoker     region      charges
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

In [10]:
type(data)

pandas.core.frame.DataFrame

In [12]:
# length of data
len(data)

1338

In [18]:
# to get the information on your columns
data.columns

Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [19]:
# Get the information on your data set
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [20]:
# indexing
data.loc[0]

age                19
gender         female
bmi              27.9
children            0
smoker            yes
region      southwest
charges     16884.924
Name: 0, dtype: object

In [21]:
# Slicing - to get the data from the specific rows
data.loc[21:25]

    age  gender     bmi  children smoker     region      charges
21   30  female  32.400         1     no  southwest   4149.73600
22   18    male  34.100         0     no  southeast   1137.01100
23   34  female  31.920         1    yes  northeast  37701.87680
24   37    male  28.025         2     no  northwest   6203.90175
25   59  female  27.720         3     no  southeast  14001.13380

In [22]:
# get a particular column - this will return you a dataframe and you can perform any function on it which is available for a dataframe
data['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [23]:
data['age'].head()

0    19
1    18
2    28
3    33
4    32
Name: age, dtype: int64

In [24]:
# filter multiple columns
data[['age', 'gender', 'region']]

      age  gender     region
0      19  female  southwest
1      18    male  southeast
2      28    male  southeast
3      33    male  northwest
4      32    male  northwest
...   ...     ...        ...
1333   50    male  northwest
1334   18  female  northeast
1335   18  female  southeast
1336   21  female  southwest
1337   61  female  northwest

[1338 rows x 3 columns]

In [26]:
# Regionwise data distribution
data['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [27]:
# Regionwise data distribution percentage wise
data['region'].value_counts(normalize=True) * 100

region
southeast    27.204783
southwest    24.289985
northwest    24.289985
northeast    24.215247
Name: proportion, dtype: float64

In [28]:
data['gender'].value_counts(normalize=True) * 100

gender
male      50.523169
female    49.476831
Name: proportion, dtype: float64

In [29]:
data['smoker'].value_counts(normalize=True) * 100

smoker
no     79.521674
yes    20.478326
Name: proportion, dtype: float64

In [ ]:
# Always calculate your value_counts on a categorical data (where data can be divided into categories like gender, regions) and not on the continuous data

In [31]:
# Average premium in a region
data.groupby(['region'])['charges'].mean()

# select region, average(charges) on a data grouped by region

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [32]:
# Average premium in a gender
data.groupby(['gender'])['charges'].mean()

gender
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [33]:
# Average premium in a smoker
data.groupby(['smoker'])['charges'].mean()

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

In [34]:
# Average premium based on region, gender and smoker level
data.groupby(['region', 'gender','smoker'])['charges'].mean()

region     gender  smoker
northeast  female  no         9640.426984
                   yes       28032.046398
           male    no         8664.042222
                   yes       30926.252583
northwest  female  no         8786.998679
                   yes       29670.824946
           male    no         8320.689321
                   yes       30713.181419
southeast  female  no         8440.205552
                   yes       33034.820716
           male    no         7609.003587
                   yes       36029.839367
southwest  female  no         8234.091260
                   yes       31687.988430
           male    no         7778.905534
                   yes       32598.862854
Name: charges, dtype: float64

In [36]:
# convert a groupby data set into a data from
grp_data = data.groupby(['region', 'gender','smoker'])['charges'].mean().reset_index()
grp_data

       region  gender smoker       charges
0   northeast  female     no   9640.426984
1   northeast  female    yes  28032.046398
2   northeast    male     no   8664.042222
3   northeast    male    yes  30926.252583
4   northwest  female     no   8786.998679
5   northwest  female    yes  29670.824946
6   northwest    male     no   8320.689321
7   northwest    male    yes  30713.181419
8   southeast  female     no   8440.205552
9   southeast  female    yes  33034.820716
10  southeast    male     no   7609.003587
11  southeast    male    yes  36029.839367
12  southwest  female     no   8234.091260
13  southwest  female    yes  31687.988430
14  southwest    male     no   7778.905534
15  southwest    male    yes  32598.862854

In [37]:
# sorting
grp_data.sort_values(by=['charges'])

       region  gender smoker       charges
10  southeast    male     no   7609.003587
14  southwest    male     no   7778.905534
12  southwest  female     no   8234.091260
6   northwest    male     no   8320.689321
8   southeast  female     no   8440.205552
2   northeast    male     no   8664.042222
4   northwest  female     no   8786.998679
0   northeast  female     no   9640.426984
1   northeast  female    yes  28032.046398
5   northwest  female    yes  29670.824946
7   northwest    male    yes  30713.181419
3   northeast    male    yes  30926.252583
13  southwest  female    yes  31687.988430
15  southwest    male    yes  32598.862854
9   southeast  female    yes  33034.820716
11  southeast    male    yes  36029.839367

In [38]:
# sorting in ascending order
grp_data.sort_values(by=['charges'], ascending=True)

       region  gender smoker       charges
10  southeast    male     no   7609.003587
14  southwest    male     no   7778.905534
12  southwest  female     no   8234.091260
6   northwest    male     no   8320.689321
8   southeast  female     no   8440.205552
2   northeast    male     no   8664.042222
4   northwest  female     no   8786.998679
0   northeast  female     no   9640.426984
1   northeast  female    yes  28032.046398
5   northwest  female    yes  29670.824946
7   northwest    male    yes  30713.181419
3   northeast    male    yes  30926.252583
13  southwest  female    yes  31687.988430
15  southwest    male    yes  32598.862854
9   southeast  female    yes  33034.820716
11  southeast    male    yes  36029.839367

In [39]:
# sorting in descending order
grp_data.sort_values(by=['charges'], ascending=False)

       region  gender smoker       charges
11  southeast    male    yes  36029.839367
9   southeast  female    yes  33034.820716
15  southwest    male    yes  32598.862854
13  southwest  female    yes  31687.988430
3   northeast    male    yes  30926.252583
7   northwest    male    yes  30713.181419
5   northwest  female    yes  29670.824946
1   northeast  female    yes  28032.046398
0   northeast  female     no   9640.426984
4   northwest  female     no   8786.998679
2   northeast    male     no   8664.042222
8   southeast  female     no   8440.205552
6   northwest    male     no   8320.689321
12  southwest  female     no   8234.091260
14  southwest    male     no   7778.905534
10  southeast    male     no   7609.003587

In [40]:
# Modify the dataframe, use inplace=True
grp_data.sort_values(by=['charges'], inplace=True)
grp_data

       region  gender smoker       charges
10  southeast    male     no   7609.003587
14  southwest    male     no   7778.905534
12  southwest  female     no   8234.091260
6   northwest    male     no   8320.689321
8   southeast  female     no   8440.205552
2   northeast    male     no   8664.042222
4   northwest  female     no   8786.998679
0   northeast  female     no   9640.426984
1   northeast  female    yes  28032.046398
5   northwest  female    yes  29670.824946
7   northwest    male    yes  30713.181419
3   northeast    male    yes  30926.252583
13  southwest  female    yes  31687.988430
15  southwest    male    yes  32598.862854
9   southeast  female    yes  33034.820716
11  southeast    male    yes  36029.839367

In [41]:
# loc -> return the dataframe based on your actual index
grp_data.loc[0]

region       northeast
gender          female
smoker              no
charges    9640.426984
Name: 0, dtype: object

In [42]:
# iloc -> return the dataframe based on your current dataset or returns data at physical position
grp_data.iloc[0]

region       southeast
gender            male
smoker              no
charges    7609.003587
Name: 10, dtype: object